const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{Dictionary: 0},
	{LocalStorage: 0},
	{Platform: 0},
	{Physics: 0},
	{Rotate: 0},
	{Player: 0},
	{BG1: 0},
	{BG2: 0},
	{Pipa_bawah: 0},
	{Pipa_atas: 0},
	{Obj_Score: 0},
	{SpriteFont: 0},
	{UI_Hitam: 0},
	{GameOver: 0},
	{Sine: 0},
	{Start1: 0},
	{Start2: 0},
	{Start3: 0},
	{Tween: 0},
	{Transition: 0},
	{Highest: 0},
	{Credits: 0},
	{GameActive: 0},
	{GameMulai: 0},
	{Data_Score: 0},
	{HScore: 0},
	{Data_Kecepatan: 0},
	{Data_WaktuSpawn: 0},
	{DataRandom: 0},
	{Masuk: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	BG1: class extends self.ITiledBackgroundInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	Pipa_bawah: class extends self.ISpriteInstance {},
	Pipa_atas: class extends self.ISpriteInstance {},
	Obj_Score: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	UI_Hitam: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Start1: class extends self.ISpriteInstance {},
	Start2: class extends self.ISpriteInstance {},
	Start3: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {},
	Highest: class extends self.ISpriteFontInstance {},
	Credits: class extends self.ITextInstance {}
}